name: Run Build and Lint Files
'on': push
jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build
          npm run lint
